force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <description>Details related to a specific FamilyLife Event</description>
    <label>Event Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Community</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Invite__c.field-meta.xml
<CustomField>
    <fullName>Invite__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Local</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Surveys_Open__c.field-meta.xml
<CustomField>
    <fullName>Surveys_Open__c</fullName>
    <description>ERT UAT</description>
    <formula>AND(
    TODAY() &gt;= Start_Date__c,
    TODAY() &lt;= End_Date__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Vital piece of information for Check in and Surveys. This is set to True when Today is greater than or equal to start date AND less than or equal to end date.</inlineHelpText>
    <label>Surveys Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>This will originally contain ERT WTR registrations, but could be expanded to other types of involvement. This is in line with Cru Schema for long term consolidation</description>
    <label>Registration</label>
    <nameField>
        <label>Involvement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for Surveys</description>
    <label>Community</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Involcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Contact_Zip__c.field-meta.xml
<CustomField>
    <fullName>Contact_Zip__c</fullName>
    <formula>Left(Contact__r.MailingPostalCode,5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event_Detail__c.field-meta.xml
<CustomField>
    <fullName>Event_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Detail</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Involvements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Flow_Choice__c.field-meta.xml
<CustomField>
    <fullName>Flow_Choice__c</fullName>
    <formula>First_Name__c &amp;&quot; &quot; &amp;  Left(Last_Name__c, 1) &amp;&quot; &quot; &amp; Left( Street__c , 30) &amp;&quot; Phone Ends With &quot; &amp;  Last_Four__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flow Choice</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations (Household)</relationshipLabel>
    <relationshipName>Involvements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Mission_Other__c.field-meta.xml
<CustomField>
    <fullName>Mission_Other__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mission Other</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WTR Registration</fullName>
            </value>
            <value>
                <fullName>Blended Registration</fullName>
            </value>
            <value>
                <fullName>LLYMI Registration</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/Staging_Survey__c.object-meta.xml
<CustomObject>
    <label>Staging Survey</label>
    <nameField>
        <displayFormat>SS{000000}</displayFormat>
        <label>Staging Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Survey__c/fields/Attendee_Id__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Id__c</fullName>
    <description>ERT</description>
    <label>Attendee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Community__c.field-meta.xml
<CustomField>
    <fullName>Community__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for Surveys</description>
    <label>Community</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <description>ERT</description>
    <label>Contact Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>ERT</description>
    <label>Event Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>ERT</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>ERT</description>
    <label>Gender</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Household_Id__c.field-meta.xml
<CustomField>
    <fullName>Household_Id__c</fullName>
    <description>ERT</description>
    <label>Household Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Invite__c.field-meta.xml
<CustomField>
    <fullName>Invite__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ERT</description>
    <label>Invite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>ERT</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ERT</description>
    <label>Local</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Mission_Other__c.field-meta.xml
<CustomField>
    <fullName>Mission_Other__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for Surveys</description>
    <label>Mission Other</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Prayer_Request__c.field-meta.xml
<CustomField>
    <fullName>Prayer_Request__c</fullName>
    <description>ERT</description>
    <label>Prayer Request</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>ERT</description>
    <label>Question</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Recommitment__c.field-meta.xml
<CustomField>
    <fullName>Recommitment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ERT</description>
    <label>Recommitment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Salvation__c.field-meta.xml
<CustomField>
    <fullName>Salvation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ERT</description>
    <label>Salvation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Small_Group__c.field-meta.xml
<CustomField>
    <fullName>Small_Group__c</fullName>
    <defaultValue>false</defaultValue>
    <description>ERT</description>
    <label>Small Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staging_Survey__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>ERT</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Evaluation</fullName>
            </value>
            <value>
                <fullName>Mission</fullName>
            </value>
            <value>
                <fullName>Oneness</fullName>
            </value>
            <value>
                <fullName>Prayer</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/flWTRGuestLocationController.cls
public without sharing class flWTRGuestLocationController {

    // --- INNER CLASS: Wrapper for Registration choices.. ---
    public class RegChoice {
        @AuraEnabled public String label { get; set; } 
        @AuraEnabled public String value { get; set; } 

        public RegChoice(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }

    // --- INNER CLASS: Wrapper for Registration lookup results ---
    public class RegFindResult {
        @AuraEnabled public String status { get; set; } // 'NONE', 'SINGLE', 'MULTI'
        @AuraEnabled public String registrationId { get; set; } // The ID, if status is 'SINGLE'
        @AuraEnabled public List<RegChoice> choices { get; set; } // The list, if status is 'MULTI'

        public RegFindResult() {
            this.status = 'NONE';
        }
    }

    // Updated to include Geolocation fields so the Client (LWC) can calculate distance.
    // This is cacheable because it returns the same list for everyone.
    @AuraEnabled(cacheable=true)
    public static List<Event_Details__c> getOpenSurveyEvents() {
        return [
            SELECT Id, Name, Event_Geo__Latitude__s, Event_Geo__Longitude__s
            FROM Event_Details__c
            WHERE Surveys_Open__c = TRUE
            ORDER BY Name ASC
        ];
    }

    @AuraEnabled
    public static String createQuestionSurvey(String eventId, String questionText, String gender) {
        if (String.isBlank(eventId) || String.isBlank(questionText)) {
            return 'Error: Event ID or question text is missing.';
        }
        try {
            Staging_Survey__c newSurvey = new Staging_Survey__c();
            newSurvey.Event_Id__c = eventId;
            newSurvey.Question__c = questionText;
            newSurvey.Type__c = 'Question';
            newSurvey.Gender__c = gender; 
            insert newSurvey;
            return 'success';
        } catch (Exception e) {
            return 'Error: Could not submit your question. ' + e.getMessage();
        }
    }

    @AuraEnabled
    public static String createPrayerSurvey(String eventId, String prayerText) {
        if (String.isBlank(eventId) || String.isBlank(prayerText)) {
            return 'Error: Event ID or prayer request text is missing.';
        }
        try {
            Staging_Survey__c newSurvey = new Staging_Survey__c();
            newSurvey.Event_Id__c = eventId;
            newSurvey.Prayer_Request__c = prayerText;
            newSurvey.Type__c = 'Prayer';
            insert newSurvey;
            return 'success';
        } catch (Exception e) {
            return 'Error: Could not submit your prayer request. ' + e.getMessage();
        }
    }

    @AuraEnabled(cacheable=true)
    public static RegFindResult findRegistrations(String eventId, String lastName, String zipCode) {
        RegFindResult result = new RegFindResult();
        
        if (String.isBlank(eventId) || String.isBlank(lastName) || String.isBlank(zipCode)) {
            return result; 
        }

        List<Registration__c> regs = [
            SELECT Id, Flow_Choice__c 
            FROM Registration__c 
            WHERE Event_Detail__c = :eventId 
              AND Last_Name__c = :lastName 
              AND Contact_Zip__c = :zipCode
            ORDER BY Flow_Choice__c ASC 
        ];

        if (regs.size() == 0) {
            result.status = 'NONE';
        } else if (regs.size() == 1) {
            result.status = 'SINGLE';
            result.registrationId = regs[0].Id;
        } else {
            result.status = 'MULTI';
            result.choices = new List<RegChoice>();
            for (Registration__c reg : regs) {
                result.choices.add(new RegChoice(reg.Flow_Choice__c, reg.Id));
            }
        }
        return result;
    }

    @AuraEnabled(cacheable=true)
    public static String getRegistrationFirstName(String registrationId) {
        if (String.isBlank(registrationId)) {
            return null;
        }
        try {
            Registration__c reg = [SELECT First_Name__c FROM Registration__c WHERE Id = :registrationId LIMIT 1];
            return reg.First_Name__c;
        } catch (Exception e) {
            return null;
        }
    }

    @AuraEnabled
    public static String createOnenessSurvey(String eventId, String registrationId, 
                                             Boolean isSalvation, Boolean isRecommitment, Boolean isCommunity) {
        
        if (String.isBlank(eventId) || String.isBlank(registrationId)) {
            return 'Error: Event or Registration is missing.';
        }
        
        try {
            Registration__c reg = [
                SELECT Id, Contact__c, Household__c 
                FROM Registration__c 
                WHERE Id = :registrationId
                LIMIT 1
            ];

            Staging_Survey__c newSurvey = new Staging_Survey__c();
            newSurvey.Event_Id__c = eventId;
            newSurvey.Type__c = 'Oneness';
            
            newSurvey.Contact_Id__c = reg.Contact__c;
            newSurvey.Household_Id__c = reg.Household__c;
            newSurvey.Attendee_Id__c = registrationId; 

            newSurvey.Salvation__c = isSalvation;
            newSurvey.Recommitment__c = isRecommitment;
            newSurvey.Community__c = isCommunity; 
            
            insert newSurvey;
            
            return 'success';

        } catch (Exception e) {
            return 'Error: Could not submit your response. ' + e.getMessage();
        }
    }

    @AURAENABLED
    public static String createMissionSurvey(String eventId, String registrationId, 
                                             Boolean inviteOthers, Boolean impactLocal, 
                                             Boolean leadSmallGroup, Boolean otherMission) { 
        
        if (String.isBlank(eventId) || String.isBlank(registrationId)) {
            return 'Error: Event or Registration is missing.';
        }

        try {
            Registration__c reg = [
                SELECT Id, Contact__c, Household__c 
                FROM Registration__c 
                WHERE Id = :registrationId
                LIMIT 1
            ];

            Staging_Survey__c newSurvey = new Staging_Survey__c();
            newSurvey.Event_Id__c = eventId;
            newSurvey.Type__c = 'Mission'; 
            
            newSurvey.Contact_Id__c = reg.Contact__c;
            newSurvey.Household_Id__c = reg.Household__c;
            newSurvey.Attendee_Id__c = registrationId; 
            
            newSurvey.Invite__c = inviteOthers;
            newSurvey.Local__c = impactLocal;
            newSurvey.Small_Group__c = leadSmallGroup;
            newSurvey.Mission_Other__c = otherMission; 
            
            insert newSurvey;
            
            return 'success';

        } catch (Exception e) {
            return 'Error: Could not submit your response. ' + e.getMessage();
        }
    }
}