force-app/main/default/objects/Account/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact</relationshipLabel>
    <relationshipName>Accounts_Households</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <description>Churches, Business, Associations, Partners, Vendors, etc.</description>
    <label>Org/Business/Church</label>
</RecordType>

force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <description>Details related to a specific FamilyLife Event</description>
    <label>Event Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/Conference_Location__c.field-meta.xml
<CustomField>
    <fullName>Conference_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account record that holds the physical location of the event</description>
    <inlineHelpText>Account Business that is specific to the actual conference location. So a convention center, resort or venue</inlineHelpText>
    <label>Event Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>012i0000000xEz5AAE</value>
        </filterItems>
        <infoMessage>Choose the Account of the Conference Location</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Details (Conference Location)</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Event End Date</description>
    <inlineHelpText>What date does this event end?</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/EventCode__c.field-meta.xml
<CustomField>
    <fullName>EventCode__c</fullName>
    <description>Unique Code assigned to this specific event</description>
    <externalId>true</externalId>
    <inlineHelpText>This is unique key that must be used across the enterprise to maintain automation. The syntax is always
&quot;WTR&quot; + Last two digits from the fiscal year of the event + Three letter code usually the nearest airport code + a single digit, normally 1. but could be 2 if there is more than one event at the location in the same fiscal year. Example WTR26TPA1</inlineHelpText>
    <label>EventCode</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Hotel_Location__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of the hotel associated with the event</description>
    <inlineHelpText>Account Business that is normally the same as the Event Location, but it is specific to sleeping rooms. So if the Hotel with Sleeping rooms is at a different Business account that would be noted here.</inlineHelpText>
    <label>Hotel Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>012i0000000xEz5AAE</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Details (Hotel Location)</relationshipLabel>
    <relationshipName>Event_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Public_Group__c</fullName>
    <label>Public Group</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>Status of the Current Event.. Note this must be in Planning for it to publish in WordPress. Changing it to any other value will prevent it from publishing.</inlineHelpText>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Event Canceled</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <isActive>false</isActive>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Staffed</fullName>
                <isActive>false</isActive>
                <label>Staffed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Event start date</description>
    <inlineHelpText>What day does this event begin?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>This will originally contain ERT WTR registrations, but could be expanded to other types of involvement. This is in line with Cru Schema for long term consolidation</description>
    <label>Registration</label>
    <nameField>
        <label>Involvement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Involcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event_Detail__c.field-meta.xml
<CustomField>
    <fullName>Event_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Detail</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Involvements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant_Type__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Type__c</fullName>
    <description>Registrant Type</description>
    <label>Registrant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Couple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C - Confirmed</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>A - Attended</fullName>
                <label>Attended</label>
            </value>
            <value>
                <fullName>N - NoShow</fullName>
                <label>Did Not Attend</label>
            </value>
            <value>
                <fullName>X - Cancelled</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Event Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <description>Registration_Type</description>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attendee</fullName>
            </value>
            <value>
                <fullName>Pastor</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/flRegistrationsControllerTest.cls
@isTest
private class flRegistrationsControllerTest {

    @TestSetup
    static void makeData() {
        // 1. Create Public Group (Setup Object) - Run as current user to avoid Mixed DML
        Group testGroup = new Group(Name = 'Test Event Group', Type = 'Regular');
        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert testGroup;
        }

        // 2 Create Account (Venue)
        Id businessAccountRtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business_Account').getRecordTypeId();
            
        Account venue = new Account(
            Name = 'Test Venue',
            RecordTypeId = businessAccountRtId,
            Type = 'WTR Venue'
        );
        insert venue;

        // 3. Create Event
        Event_Details__c evt = new Event_Details__c(
            Name = 'Test Event',
            EventCode__c = 'WTR26REG',
            Stage__c = 'Planning',
            Conference_Location__c = venue.Id,
            Hotel_Location__c = venue.Id,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addDays(3),
            Public_Group__c = testGroup.Id // Assign Group
        );
        insert evt;


        // 4. Create Contacts
        List<Contact> contacts = new List<Contact>();
        contacts.add(new Contact(FirstName = 'John', LastName = 'Doe', MailingPostalCode = '12345'));
        contacts.add(new Contact(FirstName = 'Jane', LastName = 'Doe', MailingPostalCode = '12345'));
        contacts.add(new Contact(FirstName = 'Aaron', LastName = 'Anderson', MailingPostalCode = '99999'));
        insert contacts;

        // Reg 1: Primary (Husband)
        Registration__c reg1 = new Registration__c(
            Event_Detail__c = evt.Id,
            Contact__c = contacts[0].Id, 
            Registration_Status__c = 'C - Confirmed',
            Registrant_Type__c = 'Couple',
            Registration_Type__c = 'Attendee'
        );
        insert reg1;

        List<Registration__c> additionalRegs = new List<Registration__c>();

        // Reg 2: Spouse (Wife)
        additionalRegs.add(new Registration__c(
            Event_Detail__c = evt.Id,
            Contact__c = contacts[1].Id, 
            Registration_Status__c = 'C - Confirmed',
            Registrant_Type__c = 'Couple',
            Registration_Type__c = 'Attendee'
        ));

        // Reg 3: Single
        // FIX: Changed status to 'C - Confirmed' so it is included in the controller results
        additionalRegs.add(new Registration__c(
            Event_Detail__c = evt.Id,
            Contact__c = contacts[2].Id, 
            Registration_Status__c = 'C - Confirmed', 
            Registration_Type__c = 'Attendee',
            Registrant_Type__c = 'Couple' 
        ));

        insert additionalRegs;
    }

    @isTest
    static void testGetRegistrations() {
        Event_Details__c evt = [SELECT Id FROM Event_Details__c LIMIT 1];

        Test.startTest();
        List<Registration__c> results = flRegistrationsController.getRegistrations(evt.Id);
        Test.stopTest();

        // 1. Assertion: Count
        // Now that the 3rd reg is 'Confirmed', this should return 3
        System.assertEquals(3, results.size(), 'Should return all 3 registrations linked to the event');

        // 2. Assertion: Sorting
        System.assertEquals('Anderson', results[0].Last_Name__c, 'First record should be Anderson (Alphabetical)');
        
        System.assertEquals('Doe', results[1].Last_Name__c);
        System.assertEquals('Jane', results[1].First_Name__c, 'Jane Doe should come before John Doe');
        
        System.assertEquals('Doe', results[2].Last_Name__c);
        System.assertEquals('John', results[2].First_Name__c);
    }

    @isTest
    static void testGetRegistrations_NullId() {
        Test.startTest();
        List<Registration__c> results = flRegistrationsController.getRegistrations(null);
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty list for null event ID');
    }
}