force-app/main/default/objects/Contact/fields/Is_Group_Leader__c.field-meta.xml
<CustomField>
    <fullName>Is_Group_Leader__c</fullName>
    <defaultValue>false</defaultValue>
    <description>AOPMemberGroupLeader in SPOP</description>
    <label>Is Group Leader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>This will originally contain ERT WTR registrations, but could be expanded to other types of involvement. This is in line with Cru Schema for long term consolidation</description>
    <label>Registration</label>
    <nameField>
        <label>Involvement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Involcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Contact_GC__c.field-meta.xml
<CustomField>
    <fullName>Contact_GC__c</fullName>
    <formula>Contact__r.Group_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact GC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Contact_Zip__c.field-meta.xml
<CustomField>
    <fullName>Contact_Zip__c</fullName>
    <formula>Left(Contact__r.MailingPostalCode,5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event_Detail__c.field-meta.xml
<CustomField>
    <fullName>Event_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Detail</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Involvements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/External_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Registration_Id__c</fullName>
    <label>External Registration Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Last_Event__c.field-meta.xml
<CustomField>
    <fullName>Last_Event__c</fullName>
    <formula>Contact__r.WTR_Last__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Event</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant_Type__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Type__c</fullName>
    <description>Registrant Type</description>
    <label>Registrant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Couple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C - Confirmed</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>A - Attended</fullName>
                <label>Attended</label>
            </value>
            <value>
                <fullName>N - NoShow</fullName>
                <label>Did Not Attend</label>
            </value>
            <value>
                <fullName>X - Cancelled</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Event Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <description>Registration_Type</description>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attendee</fullName>
            </value>
            <value>
                <fullName>Pastor</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Waiver__c.field-meta.xml
<CustomField>
    <fullName>Waiver__c</fullName>
    <description>Waiver</description>
    <label>Waiver</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/flRegistrationsController.cls
public with sharing class flRegistrationsController {
  @AuraEnabled(cacheable=true)
  public static List<Registration__c> getRegistrations(Id eventId) {
    if (eventId == null) {
      return new List<Registration__c>();
    }

    // MODIFIED:
    // - Added Contact_GC__c (Group Owner replacement)
    // - Added Last_Event__c (New Column)
    // - Kept Waiver__c..
    // - Removed Contact__r.Is_Group_Leader__c
    return [
      SELECT
        Id,
        Name,
        First_Name__c,
        Last_Name__c,
        Contact_Zip__c,
        Registration_Status__c,
        Registrant_Type__c,
        Registration_Type__c,
        Contact_GC__c,
        Waiver__c,
        Last_Event__c,
        External_Registration_Id__c
      FROM Registration__c
      WHERE
        Event_Detail__c = :eventId
        AND Registration_Status__c != 'X - Cancelled'
      ORDER BY Last_Name__c ASC, First_Name__c ASC
      LIMIT 2000
    ];
  }
}